# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sys_bd/sys_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd || ORIG_REF_NAME==sys_bd} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_zynq_ultra_ps_e_0_0/sys_bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==sys_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_axi_cdma_0_0/sys_bd_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_axi_cdma_0_0 || ORIG_REF_NAME==sys_bd_axi_cdma_0_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_axi_bram_ctrl_0_0/sys_bd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==sys_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_axi_bram_ctrl_0_bram_0/sys_bd_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==sys_bd_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_microblaze_0_0/sys_bd_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_microblaze_0_0 || ORIG_REF_NAME==sys_bd_microblaze_0_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_dlmb_v10_1/sys_bd_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_dlmb_v10_1 || ORIG_REF_NAME==sys_bd_dlmb_v10_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_ilmb_v10_1/sys_bd_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_ilmb_v10_1 || ORIG_REF_NAME==sys_bd_ilmb_v10_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_dlmb_bram_if_cntlr_1/sys_bd_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==sys_bd_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_ilmb_bram_if_cntlr_1/sys_bd_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==sys_bd_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_lmb_bram_1/sys_bd_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_lmb_bram_1 || ORIG_REF_NAME==sys_bd_lmb_bram_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_mdm_1_1/sys_bd_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_mdm_1_1 || ORIG_REF_NAME==sys_bd_mdm_1_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_rst_ps8_0_99M_1/sys_bd_rst_ps8_0_99M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_rst_ps8_0_99M_1 || ORIG_REF_NAME==sys_bd_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_ps8_0_axi_periph_1/sys_bd_ps8_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_ps8_0_axi_periph_1 || ORIG_REF_NAME==sys_bd_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_xbar_0/sys_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_xbar_0 || ORIG_REF_NAME==sys_bd_xbar_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_axi_mem_intercon_0/sys_bd_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_axi_mem_intercon_0 || ORIG_REF_NAME==sys_bd_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_microblaze_1_0/sys_bd_microblaze_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_microblaze_1_0 || ORIG_REF_NAME==sys_bd_microblaze_1_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_dlmb_v10_2/sys_bd_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_dlmb_v10_2 || ORIG_REF_NAME==sys_bd_dlmb_v10_2} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_ilmb_v10_2/sys_bd_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_ilmb_v10_2 || ORIG_REF_NAME==sys_bd_ilmb_v10_2} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_dlmb_bram_if_cntlr_2/sys_bd_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==sys_bd_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_ilmb_bram_if_cntlr_2/sys_bd_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==sys_bd_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_lmb_bram_2/sys_bd_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_lmb_bram_2 || ORIG_REF_NAME==sys_bd_lmb_bram_2} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/sys_bd_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_axi_smc_1 || ORIG_REF_NAME==sys_bd_axi_smc_1} -quiet] -quiet

# Block Designs: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/bd_389c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_0/bd_389c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_1/bd_389c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_2/bd_389c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_3/bd_389c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_4/bd_389c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_5/bd_389c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_6/bd_389c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_7/bd_389c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_8/bd_389c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_9/bd_389c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_10/bd_389c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_11/bd_389c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_12/bd_389c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_13/bd_389c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_14/bd_389c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_15/bd_389c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_16/bd_389c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_17/bd_389c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_18/bd_389c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_19/bd_389c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_20/bd_389c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_21/bd_389c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_22/bd_389c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_23/bd_389c_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_24/bd_389c_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_25/bd_389c_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_26/bd_389c_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_27/bd_389c_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_28/bd_389c_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_29/bd_389c_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd/ip/sys_bd_axi_mem_intercon_1_0/sys_bd_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_axi_mem_intercon_1_0 || ORIG_REF_NAME==sys_bd_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_auto_ds_0/sys_bd_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_auto_ds_0 || ORIG_REF_NAME==sys_bd_auto_ds_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_auto_pc_0/sys_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_auto_pc_0 || ORIG_REF_NAME==sys_bd_auto_pc_0} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_auto_pc_1/sys_bd_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_auto_pc_1 || ORIG_REF_NAME==sys_bd_auto_pc_1} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_auto_pc_2/sys_bd_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_auto_pc_2 || ORIG_REF_NAME==sys_bd_auto_pc_2} -quiet] -quiet

# IP: bd/sys_bd/ip/sys_bd_auto_us_0/sys_bd_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_auto_us_0 || ORIG_REF_NAME==sys_bd_auto_us_0} -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_zynq_ultra_ps_e_0_0/sys_bd_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_zynq_ultra_ps_e_0_0/sys_bd_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==sys_bd_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_axi_cdma_0_0/sys_bd_axi_cdma_0_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_cdma_0_0/sys_bd_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_axi_cdma_0_0 || ORIG_REF_NAME==sys_bd_axi_cdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_axi_bram_ctrl_0_bram_0/sys_bd_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_microblaze_0_0/sys_bd_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_microblaze_0_0 || ORIG_REF_NAME==sys_bd_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_microblaze_0_0/sys_bd_microblaze_0_0_ooc_debug.xdc

# XDC: bd/sys_bd/ip/sys_bd_dlmb_v10_1/sys_bd_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_dlmb_v10_1 || ORIG_REF_NAME==sys_bd_dlmb_v10_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_ilmb_v10_1/sys_bd_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_ilmb_v10_1 || ORIG_REF_NAME==sys_bd_ilmb_v10_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_lmb_bram_1/sys_bd_lmb_bram_1_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_mdm_1_1/sys_bd_mdm_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_mdm_1_1 || ORIG_REF_NAME==sys_bd_mdm_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_mdm_1_1/sys_bd_mdm_1_1_ooc_trace.xdc

# XDC: bd/sys_bd/ip/sys_bd_rst_ps8_0_99M_1/sys_bd_rst_ps8_0_99M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_rst_ps8_0_99M_1 || ORIG_REF_NAME==sys_bd_rst_ps8_0_99M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_rst_ps8_0_99M_1/sys_bd_rst_ps8_0_99M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_rst_ps8_0_99M_1 || ORIG_REF_NAME==sys_bd_rst_ps8_0_99M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_microblaze_1_0/sys_bd_microblaze_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_microblaze_1_0 || ORIG_REF_NAME==sys_bd_microblaze_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_microblaze_1_0/sys_bd_microblaze_1_0_ooc_debug.xdc

# XDC: bd/sys_bd/ip/sys_bd_dlmb_v10_2/sys_bd_dlmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_dlmb_v10_2 || ORIG_REF_NAME==sys_bd_dlmb_v10_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_ilmb_v10_2/sys_bd_ilmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_ilmb_v10_2 || ORIG_REF_NAME==sys_bd_ilmb_v10_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_lmb_bram_2/sys_bd_lmb_bram_2_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_1/bd_389c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_1/bd_389c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_2/bd_389c_arsw_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_3/bd_389c_rsw_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_4/bd_389c_awsw_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_5/bd_389c_wsw_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_6/bd_389c_bsw_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_10/bd_389c_s00a2s_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_11/bd_389c_sarn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_12/bd_389c_srn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_13/bd_389c_sawn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_14/bd_389c_swn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_15/bd_389c_sbn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_16/bd_389c_m00s2a_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_17/bd_389c_m00arn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_18/bd_389c_m00rn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_19/bd_389c_m00awn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_20/bd_389c_m00wn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_21/bd_389c_m00bn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_23/bd_389c_m01s2a_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_24/bd_389c_m01arn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_25/bd_389c_m01rn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_26/bd_389c_m01awn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_27/bd_389c_m01wn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_axi_smc_1/bd_0/ip/ip_28/bd_389c_m01bn_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_auto_ds_0/sys_bd_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_auto_ds_0 || ORIG_REF_NAME==sys_bd_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_auto_ds_0/sys_bd_auto_ds_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_auto_pc_0/sys_bd_auto_pc_0_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_auto_pc_1/sys_bd_auto_pc_1_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_auto_pc_2/sys_bd_auto_pc_2_ooc.xdc

# XDC: bd/sys_bd/ip/sys_bd_auto_us_0/sys_bd_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_auto_us_0 || ORIG_REF_NAME==sys_bd_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/sys_bd/ip/sys_bd_auto_us_0/sys_bd_auto_us_0_ooc.xdc

# XDC: bd/sys_bd/sys_bd_ooc.xdc
